routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome',['name'=>'mgmg']);
//     // return 'Hello Laravel';
// });

Route::get('/','PostController@index');

Route::resource('/post','PostController');

Route::resource('/category','CategoryController');
Route::post('/comment','CommentController@store')->name('comment');

// Buildin auth routes
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// For Admin auth
Route::prefix('admin')->group(function () {
    Route::get('dashboard', 'HomeController@index')->name('admin.dashboard');
    Route::get('register', 'AdminController@create')->name('admin.register');
    Route::post('register', 'AdminController@store')->name('admin.register.store');
    Route::get('login', 'AdminController@login')->name('admin.auth.login');
    Route::post('login', 'AdminController@loginAdmin')->name('admin.auth.loginAdmin');
    Route::post('logout', 'AdminController@logout')->name('admin.auth.logout');
  });

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title','body','photo','user_id','category_id'
    ];

    public function user()
    {
    	return $this->belongsTo('App\User');
    }

    public function comments()
    {
    	return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Resources\PostResource;
use App\Http\Controllers\Api\BaseController as BaseController;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Post;
use Auth;
use Validator;
class PostController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        // $posts = Post::all();
        // return $posts;
        return PostResource::collection(Post::all());
        // return $this->sendResponse(PostResource::collection(Post::all()),'Posts retrieved successfully.');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $input = $request->all();

        $validator = Validator::make($input, [
            'title' => 'required|min:2',
            'body' => 'required|min:10',
            'photo' => 'required|mimes:jpeg,png,jpg,gif|max:2048',
            'category' => 'required|integer'
        ]);


        if($validator->fails()){
            // return $this->sendError('Validation Error.', $validator->errors());
            return $validator->errors();
        }

        if($request->hasfile('photo')){
            $photo = $request->file('photo');
            $name = $photo->getClientOriginalName();
            $photo->move(public_path().'/storage/image/',$name);
            $photo = '/storage/image/'.$name;
        }

        $post = Post::create([
            'title' => request('title'),
            'body' => request('body'),
            'photo' => $photo,
            'user_id' => Auth::id(),
            'category_id' => request('category')
        ]);

        if (is_null($post)) {
            // return $this->sendError('Unauthorized');
            return response()->json([
                'message' => 'Unauthorized'
            ], 401);
        }

        // return $this->sendResponse(PostResource($post), 'Post created successfully.');
        return new PostResource($post);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $post = Post::find($id);
        // return $post;
        // if (is_null($post)) {
        //     return $this->sendError('Product not found.');
        // }

        // return $this->sendResponse(PostResource::collection($post));
        return new PostResource($post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $input = $request->all();


        $validator = Validator::make($input, [
            'title' => 'required|min:2',
            'body' => 'required|min:10',
            'oldphoto' => 'required',
            // 'photo' => 'required|mimes:jpeg,png,jpg,gif|max:2048',
            'category' => 'required|integer'
        ]);


        if($validator->fails()){
            return $this->sendError('Validation Error.', $validator->errors());
            // return $validator->errors();
        }

        if($request->hasfile('photo')){
            $photo = $request->file('photo');
            $name = $photo->getClientOriginalName();
            $photo->move(public_path().'/storage/image/',$name);
            $photo = '/storage/image/'.$name;
        }else{
            $photo = $request->oldphoto;
        }

        $post = Post::find($id);
        $post->title = request('title');
        $post->body = request('body');
        $post->photo = $photo;
        $post->user_id = Auth::id();
        $post->category_id = request('category');
        $post->save();

        if (is_null($post)) {
            return $this->sendError('Unauthorized');
        }

        // return $this->sendResponse(PostResource($post), 'Post created successfully.');
        return new PostResource($post);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $post = Post::find($id);
        $post->delete();

        // return $this->sendResponse(PostResource($post), 'Post deleted successfully.');
        return new PostResource($post);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Post;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth',['except'=>['index','show']]);
        // $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // return 'index function of PostController';
        // $posts = Post::all();

        // if ($user_id = request('user_id')) {
        //     $posts = Post::where('user_id', $user_id)
        //        ->orderBy('id', 'desc')
        //        ->get();
        // }

        // if ($category_id = request('category_id')) {
        //     $posts = Post::where('category_id', $category_id)
        //        ->orderBy('id', 'desc')
        //        ->get();
        // }

        // return view('post.read',compact('posts'));
        return view('post.read');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // print_r($request->all());

        $this->validate($request,[
            'title' => 'required|min:2',
            'body' => 'required|min:10',
            'photo' => 'required|mimes:jpeg,png,jpg,gif|max:2048',
            'category' => 'required|integer'
        ]);

        if($request->hasfile('photo')){
            $photo = $request->file('photo');
            $name = $photo->getClientOriginalName();
            $photo->move(public_path().'/storage/image/',$name);
            $photo = '/storage/image/'.$name;
        }

        // $post = new Post();
        // $post->title = $request->title;
        // $post->body = $request->body;
        // $post->photo = 'photo';
        // $post->user_id = 1;
        // $post->category_id = $request->category;
        // $post->save();

        Post::create([
            'title' => request('title'),
            'body' => request('body'),
            'photo' => $photo,
            'user_id' => Auth::id(),
            'category_id' => request('category')
        ]);

        return redirect()->route('post.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $post = Post::find($id);
        return view('post.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $post = Post::find($id);
        return view('post.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[
            'title' => 'required|min:2',
            'body' => 'required|min:10',
            'oldphoto' => 'required',
            // 'photo' => 'required|mimes:jpeg,png,jpg,gif|max:2048',
            'category' => 'required|integer'
        ]);

        if($request->hasfile('photo')){
            $photo = $request->file('photo');
            $name = $photo->getClientOriginalName();
            $photo->move(public_path().'/storage/image/',$name);
            $photo = '/storage/image/'.$name;
        }else{
            $photo = $request->oldphoto;
        }

        $post = Post::find($id);
        $post->title = $request->title;
        $post->body = $request->body;
        $post->photo = $photo;
        $post->user_id = Auth::id();
        $post->category_id = $request->category;
        $post->save();

        return redirect()->route('post.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function destroy($id)
    {
        //
        $post = Post::find($id);

        $post->delete();

        return redirect()->route('post.index');
    }
}

resources/views/post/create.blade.php
@extends('frontend')
@section('content')
<div class="col-md-8">

    <h1 class="my-4">Upload
    <small>Blog Post</small>
    </h1>
    <!-- Error Msg -->
    
    <!-- Create Page -->

    <form method="post" action="{{route('post.store')}}" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="">Title:</label>
            <input type="text"
            class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" id="" aria-describedby="helpId" placeholder="" value="{{ old('title') }}" required autofocus>
            @if ($errors->has('title'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('title') }}</strong>
                </span>
            @endif
        </div>
        <div class="form-group">
            <label for="">Body:</label>
            <textarea class="form-control{{ $errors->has('body') ? ' is-invalid' : '' }}" name="body" id="" aria-describedby="helpId" placeholder="" required autofocus>{{ old('body') }}</textarea>
            @if ($errors->has('body'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('body') }}</strong>
                </span>
            @endif
        </div>
        <div class="form-group">
            <label for="">Photo:</label>
            <input type="file"
            class="form-control-file{{ $errors->has('photo') ? ' is-invalid' : '' }}" name="photo" id="" aria-describedby="helpId" placeholder="">
            @if ($errors->has('photo'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('photo') }}</strong>
                </span>
            @endif
        </div>
        <div class="form-group">
            <label for="">Category:</label>
            <select name="category" class="form-control">
            <option value="">Select Category</option>
            @foreach($categories as $category)
                <option value="{{$category->id}}">{{$category->name}}</option>
            @endforeach
            </select>
            @if ($errors->has('category'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('category') }}</strong>
                </span>
            @endif
        </div>
        <div class="form-group">
            <input type="submit"
            class="btn btn-info" name="btnsubmit" id="" aria-describedby="helpId" placeholder="" value="Save">
        </div>
    </form>

</div>
@endsection

resources/views/post/edit.blade.php
@extends('frontend')
@section('content')
<div class="col-md-8">

    <h1 class="my-4">Page Heading
    <small>Secondary Text</small>
    </h1>

    <!-- Create Page -->

    <form method="post" action="{{route('post.update',$post->id)}}" enctype="multipart/form-data">
    @method('PATCH')
    @csrf
        <div class="form-group">
            <label for="">Title:</label>
            <input type="text"
            class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" id="" aria-describedby="helpId" placeholder="" value="{{ $post->title }}" required autofocus>
            @if ($errors->has('title'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('title') }}</strong>
                </span>
            @endif
        </div>
        <div class="form-group">
            <label for="">Body:</label>
            <textarea class="form-control{{ $errors->has('body') ? ' is-invalid' : '' }}" name="body" id="" aria-describedby="helpId" placeholder="" required autofocus>{{ $post->body }}</textarea>
            @if ($errors->has('body'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('body') }}</strong>
                </span>
            @endif
        </div>
        <div class="form-group">
            <label for="">Photo:</label>

            <nav>
              <div class="nav nav-tabs">
                <a class="nav-item nav-link active" data-toggle="tab" href="#old">Old</a>
                <a class="nav-item nav-link" data-toggle="tab" href="#new">New</a>
              </div>
            </nav>

            <div class="tab-content mt-3">
              <div class="tab-pane fade show active" id="old">
                <img src="{{$post->photo}}" width="100" height="100">
                <input type="hidden" value="{{$post->photo}}" name="oldphoto">
              </div>

              <div class="tab-pane fade" id="new">
                <input type="file"
                class="form-control-file{{ $errors->has('photo') ? ' is-invalid' : '' }}" name="photo" id="" aria-describedby="helpId" placeholder="">
                @if ($errors->has('photo'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('photo') }}</strong>
                    </span>
                @endif
              </div>
            </div>  
            
        </div>
        <div class="form-group">
            <label for="">Category:</label>
            <select name="category" class="form-control">
            <option value="">Select Category</option>
            @foreach($categories as $category)
                <option value="{{$category->id}}" @if($post->category_id == $category->id) {{'selected'}} @endif>{{$category->name}}</option>
            @endforeach
            </select>
            @if ($errors->has('category'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('category') }}</strong>
                </span>
            @endif
        </div>
        <div class="form-group">
            <input type="submit"
            class="btn btn-info" name="btnsubmit" id="" aria-describedby="helpId" placeholder="" value="Save">
        </div>
    </form>

</div>
@endsection

resources/views/post/read.blade.php
@extends('frontend')
@section('content')
<allposts></allposts>
@endsection

resources/views/post/show.blade.php
@extends('frontend')
@section('content')
<div class="col-md-8">

    <!-- Title -->
    <h1 class="mt-4">{{ $post->title }}</h1>

    <!-- Author -->
    <p class="lead">
    by
    <a href="/post/?user_id={{$post->user_id}}">{{$post->user->name}}</a>
    </p>

    <hr>

    <!-- Date/Time -->
    <p>
        Posted on {{ $post->created_at->toDayDateTimeString() }}
    </p> 

    @if(Auth::check() && (Auth::id() == $post->user_id))
    <a href="{{route('post.edit',$post->id)}}" class="btn btn-warning btn-sm mr-2">Edit</a>    
    
    <form action="{{ route('post.destroy', $post->id)}}" method="post" class="mt-2">
        @csrf
        @method('DELETE')
        <button class="btn btn-danger btn-sm" type="submit">Delete</button>
    </form>
    @endif

    <hr>

    <!-- Preview Image -->
    <img class="img-fluid rounded" src="{{ $post->photo }}" alt="">

    <hr>

    <!-- Post Content -->
    <p class="lead">{{ $post->body }}</p>

    <hr>

    <!-- Comments Form -->
    <div class="card my-4">
    <h5 class="card-header">Leave a Comment:</h5>
    <div class="card-body">
        
        <input type="hidden" name="postid" value="{{$post->id}}" id="postid">
        <div class="form-group">
            <textarea class="form-control" rows="3" name="comment" id="body"></textarea>
        </div>
        <button type="button" class="btn btn-primary addcomment">Submit</button>
        
    </div>
    </div>

    @foreach($post->comments as $comment)
    <!-- Single Comment -->
    <div class="media mb-4">
    <!-- <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt=""> -->
    <div class="media-body">
        <h5 class="mt-0">{{$comment->user->name}}</h5>
        {{$comment->body}}
        {{$comment->created_at->diffForHumans()}}
    </div>
    </div>
    @endforeach
</div>
@endsection

@section('script')
    <script type="text/javascript">
        $(document).ready(function () {

            $('.addcomment').on('click',function () {
                var postid = $('#postid').val();
                var body = $('#body').val();
                // alert(postid + body);

                $.ajaxSetup({
                  headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                  }
                });

                $.ajax({
                  method: 'post',
                  url: '/comment',
                  data: {postid:postid,body:body},
                  success:function (response) {
                      alert(response);
                  }
                })
            })

        })
    </script>
@endsection