routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome',['name'=>'mgmg']);
//     // return 'Hello Laravel';
// });

Route::get('/','PostController@index');

Route::resource('/post','PostController');

Route::resource('/category','CategoryController');
Route::post('/comment','CommentController@store')->name('comment');

// Buildin auth routes
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// For Admin auth
Route::prefix('admin')->group(function () {
    Route::get('dashboard', 'HomeController@index')->name('admin.dashboard');
    Route::get('register', 'AdminController@create')->name('admin.register');
    Route::post('register', 'AdminController@store')->name('admin.register.store');
    Route::get('login', 'AdminController@login')->name('admin.auth.login');
    Route::post('login', 'AdminController@loginAdmin')->name('admin.auth.loginAdmin');
    Route::post('logout', 'AdminController@logout')->name('admin.auth.logout');
  });

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name'
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $allcategories = Category::paginate(10);

        return view('category.read',compact('allcategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $this->validate($request,[
            'name' => 'required|min:5'
        ]);

        Category::create([
            'name' => request('name')
        ]);

        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
<div class="col-md-8">
    <h1 class="my-4">Create
    <small>New Category</small>
    </h1>
    <!-- Error Msg -->
    
    <!-- Create Page -->

    <form method="post" action="{{route('category.store')}}">
    @csrf
        <div class="form-group">
            <label for="">Category Name:</label>
            <input type="text"
            class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="" aria-describedby="helpId" placeholder="" value="{{ old('name') }}" required autofocus>
            @if ($errors->has('name'))
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
        </div>

        <div class="form-group">
            <input type="submit"
            class="btn btn-info" name="btnsubmit" id="" aria-describedby="helpId" placeholder="" value="Save">
        </div>
    </form>
</div>
    </div>
</div>
@endsection

resources/views/category/read.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
<div class="col-md-8">

    <h1 class="my-4">Category Page
    <small>Secondary Text</small>

    <a href="{{route('category.create')}}" class="btn btn-info float-right">Add Category</a>
    </h1>

    <!-- All Category -->
    <table class="table hovered">
        <thead>
            <tr>
                <th>No</th>
                <th>Category Name</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody>
        @foreach($allcategories as $category)
            <tr>
                <td>{{$category->id}}</td>
                <td>{{$category->name}}</td>
                <td>
                <a href="{{route('category.index')}}" class="btn btn-warning">Edit</a>
                <a href="{{route('category.index')}}" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {{ $allcategories->links() }}
</div>
    </div>
</div>

@endsection