routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome',['name'=>'mgmg']);
//     // return 'Hello Laravel';
// });

Route::get('/','PostController@index');

Route::resource('/post','PostController');

Route::resource('/category','CategoryController');
Route::post('/comment','CommentController@store')->name('comment');

// Buildin auth routes
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// For Admin auth
Route::prefix('admin')->group(function () {
    Route::get('dashboard', 'HomeController@index')->name('admin.dashboard');
    Route::get('register', 'AdminController@create')->name('admin.register');
    Route::post('register', 'AdminController@store')->name('admin.register.store');
    Route::get('login', 'AdminController@login')->name('admin.auth.login');
    Route::post('login', 'AdminController@loginAdmin')->name('admin.auth.loginAdmin');
    Route::post('logout', 'AdminController@logout')->name('admin.auth.logout');
  });

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
            <a class="navbar-brand" href="#">Admin Dashboard</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                  @if (!Auth::guard('admin')->check())
                        <li class="nav-item">
                          <a class="nav-link" href="{{route('admin.auth.login')}}">Login</a>
                        </li>
                      @if (Route::has('register'))
                        <li class="nav-item">
                          <a class="nav-link" href="{{route('admin.register')}}">Sign Up</a>
                        </li>
                      @endif
                  @else

                      <li class="nav-item">
                          <a class="nav-link" href="{{route('category.index')}}">Category</a>
                      </li>
                      <li class="nav-item dropdown">
                          <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                              {{ Auth('admin')->user()->name }} <span class="caret"></span>
                          </a>

                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="{{ route('admin.auth.logout') }}"
                                  onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                  {{ __('Logout') }}
                              </a>

                              <form id="logout-form" action="{{ route('admin.auth.logout') }}" method="POST" style="display: none;">
                                  @csrf
                              </form>
                          </div>
                      </li>
                  @endif

                  
                </ul>
            </div>
            </div>
        </nav>

        <main class="py-4 my-5">
            @yield('content')
        </main>
    </div>
</body>
</html>